version: '{branch}-{build}'

environment:
  matrix:
    - arch: x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: Visual Studio 14 2015
      CMAKE_CONFIG: Debug
      PY_PYTHON: 2.7-32
      USE_PIP: 1
    - arch: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 15 2017 Win64
      CMAKE_CONFIG: Release
      PY_PYTHON: 3.5
    - arch: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_GENERATOR: Visual Studio 16 2019
      CMAKE_CONFIG: Debug
      USE_PIP: 1
    - arch: x86
      CMAKE_GENERATOR: MSYS Makefiles
      CMAKE_CONFIG: RelWithDebInfo
      PY_PYTHON: 3.5-32
      BINDIR: C:\MinGW\bin
    - arch: x64
      CMAKE_GENERATOR: MinGW Makefiles
      CMAKE_CONFIG: MinSizeRel
      PY_PYTHON: 3.6
      BINDIR: 'C:\msys64\mingw64\bin;C:\msys64\usr\bin'
      USE_PIP: 1

build_script:
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" (del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets")
# CMake protests against sh.exe in PATH for MinGW Makefiles
- if defined BINDIR (set "PATH=%PATH:C:\Program Files (x86)\Git\bin;=%")
- if defined BINDIR (set "PATH=%PATH:C:\Program Files\Git\usr\bin;=%")
- if defined BINDIR (set "PATH=%BINDIR%;%PATH%")
- cmake -G "%CMAKE_GENERATOR%" .
- cmake --build . --config %CMAKE_CONFIG%
- cmake --build . --config %CMAKE_CONFIG% --target check
- py -c "import sys; print(sys.version+'\n'+sys.executable)"
- py -m pip install pybind11
- cmd: 'if [%PY_PYTHON%]==[2.7-32] "%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %ARCH%'
- if     defined USE_PIP (py -m pip install --upgrade .)
- if not defined USE_PIP (py setup.py install)

test_script:
- ctest -C "%CMAKE_CONFIG%" --output-on-failure
- py -m unittest discover -v -s tests/
