version: '{branch}-{build}'

environment:
  matrix:
    - arch: x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: Visual Studio 14 2015
      CMAKE_CONFIG: Debug
      PYEXE: C:\Python36\python.exe
      PY_PYTHON3: 3.5-32
    - arch: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 15 2017 Win64
      CMAKE_CONFIG: Release
      PYEXE: C:\Python36-x64\python.exe

build_script:
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" (del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets")
- cmake -G "%CMAKE_GENERATOR%" .
- cmake --build . --config %CMAKE_CONFIG%
- py --version
- py -c "import sys; print(sys.executable)"
- py setup.py sdist
- py -m pip install --verbose dist\gemmi-*.tar.gz
- py -2 --version
- py -2 -c "import sys; print(sys.executable)"

test_script:
- py -m unittest discover -v -s tests/
- cmake --build . --config %CMAKE_CONFIG% --target test
