version: '{branch}-{build}'

environment:
  matrix:
    - arch: x86
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CMAKE_GENERATOR: Visual Studio 14 2015
      CMAKE_CONFIG: Debug
      PY_PYTHON3: 3.5-32
      PY_PYTHON2: 2.7-32
    - arch: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      CMAKE_GENERATOR: Visual Studio 15 2017 Win64
      CMAKE_CONFIG: Release

build_script:
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" (del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets")
- cmake -G "%CMAKE_GENERATOR%" .
- cmake --build . --config %CMAKE_CONFIG%
- cmake --build . --config %CMAKE_CONFIG% --target check
- py -3 -c "import sys; print(sys.version+'\n'+sys.executable)"
- py -3 -m pip install --upgrade .
- cmd: '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %ARCH%'
- py -2 -c "import sys; print(sys.version+'\n'+sys.executable)"
- py -2 -m pip install --upgrade .

test_script:
- ctest -C "%CMAKE_CONFIG%" --output-on-failure
- py -3 -m unittest discover -v -s tests/
- py -2 -m unittest discover -v -s tests/
