language: cpp
git:
  depth: 3
sudo: false

matrix:
  include:
  - os: linux
    dist: trusty
    addons:
      apt:
        packages: [libz-dev, gfortran]
    compiler: gcc
    env:
      - COMPILER=g++-4.8
      - FC=gfortran-4.8
    after_script:
      - python setup.py install --user --prefix=
      - python -m unittest discover -v -s tests/

  - os: linux
    dist: trusty
    addons:
      apt:
        packages: [libz-dev, python3-pip, clang-3.4]
    env:
      - COMPILER=/usr/bin/clang++
    after_script:
      - python3 setup.py install --user --prefix=
      - python3 -m unittest discover -v -s tests/

  - os: linux
    dist: xenial
    addons:
      apt:
        packages: [g++]
    env:
      - COMPILER=/usr/bin/g++
      - CMAKE_ARGS="-D USE_PYTHON=1"
    after_script:
      - python -m unittest discover -v -s tests/

  - os: linux
    dist: bionic
    addons:
      apt:
        packages: [g++, gfortran, libz-dev]
    env:
      - COMPILER=/usr/bin/g++
      - FC=gfortran
    after_script:
      - python setup.py sdist
      - python -m pip install dist/gemmi-*.tar.gz
      - python -m unittest discover -v -s tests/

  - os: osx
    #osx_image: xcode8.3
    compiler: clang
    env: COMPILER=clang++
    after_script:
      - python3 setup.py install --user --prefix=
      - python3 -m unittest discover -v -s tests/

script:
  - $COMPILER --version
  - CXX=$COMPILER cmake . $CMAKE_ARGS
  - make -j2
  - make check -j2
