language: cpp
git:
  depth: 3
sudo: false

matrix:
  include:
  - os: linux
    dist: trusty
    addons:
      apt:
        packages: [libz-dev, gfortran]
    compiler: gcc
    env:
      - COMPILER=g++-4.8
      - FC=gfortran-4.8
    script:
      - $COMPILER --version
      - CXX=$COMPILER cmake .
      - make -j2
      - make check -j2
      - python setup.py install --user --prefix=
      - python -m unittest discover -v -s tests/

  - os: linux
    dist: trusty
    addons:
      apt:
        packages: [libz-dev, python3-pip, clang-3.4]
    env:
      - COMPILER=/usr/bin/clang++
    script:
      - $COMPILER --version
      - CXX=$COMPILER cmake .
      - make -j2
      - make check -j2
      - python3 setup.py install --user --prefix=
      - python3 -m unittest discover -v -s tests/

  - os: linux
    dist: xenial
    addons:
      apt:
        packages: [g++]
    env:
      - COMPILER=/usr/bin/g++
    script:
      - |
        $COMPILER --version
        mkdir build
        git clone --depth=1 https://github.com/pybind/pybind11.git
        cd pybind11
        cmake -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -DPYBIND11_TEST=OFF .
        make install
        cd ../build
        CXX=$COMPILER cmake -DUSE_PYTHON=1 -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 ..
        make -j2
        make check -j2
        python -m unittest discover -v -s ../tests/

  - os: linux
    dist: bionic
    addons:
      apt:
        packages: [g++, gfortran, libz-dev]
    env:
      - COMPILER=/usr/bin/g++
      - FC=gfortran
    script:
      - $COMPILER --version
      - CXX=$COMPILER cmake .
      - make -j2
      - make check -j2
      - python setup.py sdist
      - python -m pip install dist/gemmi-*.tar.gz
      - python -m unittest discover -v -s tests/

  - os: osx
    #osx_image: xcode8.3
    compiler: clang
    env: COMPILER=clang++
    script:
      - $COMPILER --version
      - CXX=$COMPILER cmake .
      - make -j2
      - make check -j2
      - python3 setup.py install --user --prefix=
      - python3 -m unittest discover -v -s tests/
