language: cpp
sudo: false
addons:
  apt:
    packages: [libz-dev]

matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - COMPILER=g++-4.8
      - PYTHON=python3
      - WARN="-Wno-missing-field-initializers -Wno-shadow"

  - os: osx
    osx_image: xcode7.3
    compiler: clang
    env: COMPILER=clang++

script:
  - make -j2 CXX=${COMPILER:-c++} EXTRA_WFLAGS="$WARN"
  - make write-help
  - ${PYTHON:-python} setup.py install --user
  - ${PYTHON:-python} -m unittest discover -s tests/
