language: cpp
sudo: false
addons:
  apt:
    packages: [libz-dev]

matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
    env: COMPILER=g++-4.8

  - os: osx
    osx_image: xcode7.3
    compiler: clang
    env: COMPILER=clang++PYTHON=2.7 CPP=14 CLANG

script:
  - make -j2 CXX=$COMPILER
  - make write-help
# - make py
# - python -m unittest discover -s tests/
