language: cpp
sudo: false
addons:
  apt:
    packages: [libz-dev]

matrix:
  include:
  - os: linux
    dist: trusty
    compiler: gcc
    env:
      - COMPILER=g++-4.8
      - PYTHON=python
      - WARN="-Wno-missing-field-initializers -Wno-shadow"

  - os: osx
    osx_image: xcode7.3
    compiler: clang
    env: COMPILER=clang++ PYTHON=python

install:
  - $PYTHON -m pip install --user pybind11
script:
  - make -j2 CXX=$COMPILER EXTRA_WFLAGS="$WARN"
  - make write-help
  - $PYTHON setup.py install --user --prefix=
  - $PYTHON -m unittest discover -v -s tests/
